rerank:
  likes:
    - "DeepSeek-R1: Incentivizing Reasoning Capability in LLMs via Reinforcement Learning"
    - "QWEN2.5-MATH TECHNICAL REPORT: TOWARD MATHEMATICAL EXPERT MODEL VIA SELF-IMPROVEMENT"
    - "DeepSeekMath: Pushing the Limits of Mathematical Reasoning in Open Language Models"
    - "Seed-Thinking-v1.5: Advancing Superb Reasoning Models with Reinforcement Learning"
    - "VAPO: Efficient and Reliable Reinforcement Learning for Advanced Reasoning Tasks"
    - "Critique Fine-Tuning: Learning to Critique is More Effective than Learning to Imitate"
    - "SFT Memorizes, RL Generalizes: A Comparative Study of Foundation Model Post-training"
    - "Does Reinforcement Learning Really Incentivize Reasoning Capacity in LLMs Beyond the Base Model?"
    - "Chain-of-thought prompting elicits reasoning in large language models"
    - "What’s behind ppo’s collapse in long-cot? value optimization holds the secret"
    - "TTRL: Test-Time Reinforcement Learning"
    - "AlphaEvolve: A coding agent for scientific and algorithmic discovery"
    - "Mining Hidden Thoughts from Texts: Evaluating Continual Pretraining with Synthetic Data for LLM Reasoning"
    - "Scaling Laws of Synthetic Data for Language Models"
    - "Rephrasing the Web: A Recipe for Compute and Data-Efficient Language Modeling"
  dislikes:
    - "RobustEMD: Domain Robust Matching for Cross-domain Few-shot Medical Image Segmentation"
    - "Semantic Segmentation of Unmanned Aerial Vehicle Remote Sensing Images using SegFormer"
    - "Y-CA-Net: A Convolutional Attention Based Network for Volumetric Medical Image Segmentation"
    - "LightM-UNet: Mamba Assists in Lightweight UNet for Medical Image Segmentation"
    - "Denoising diffusion probabilistic models for 3D medical image generation"
    - "The Segment Anything Model (SAM) for Remote Sensing Applications: From Zero to One Shot"
    - "OpenAI融资70亿，只剩孤家寡人？众人怒揭奥特曼真面目"
    - "Pika 1.5重磅升级！万物皆可爆炸，搞笑特效全网病毒式疯传"
    - "MIT系初创打破Transformer霸权！液体基础模型刷新SOTA，非GPT架构首次显著超越Transformer"
    - "Ilya预言错了！华人Nature一作给RLHF“判死刑”，全球大模型都不可靠"
    - "群体智能”剑指AGI革命！国产架构挑战Transformer霸权，首款非Attention模型更新"
    - "准确率飙升46%！耶鲁-斯坦福「自更新记忆库」新框架，重塑LLM化学推理能力"
    - "CVPR 2025 | 双目匹配新突破！DEFOM-Stereo高效利用单目深度基础模型"
    - "炸裂！又一个AI大模型的新方向，彻底爆了！"
    - "「天工Ultra」半马夺冠，人形机器人通关产业落地第一关"
    - "FedBiP: Heterogeneous One-Shot Federated Learning with Personalized Latent Diffusion Models"
    - "Learning De-Biased Representations for Remote-Sensing Imagery"
    - "Brain Mapping with Dense Features: Grounding Cortical Semantic Selectivity in Natural Images With Vision Transformers"
    - "Art Forgery Detection using Kolmogorov Arnold and Convolutional Neural Networks"
    - "Synthetic Generation of Dermatoscopic Images with GAN and Closed-Form Factorization"
    - "AMD AI PC大赛重磅来袭！13万奖金池，NPU算力免费用，速来组队瓜分奖金！"
    - "博士申请 | 中佛罗里达大学计算机系尚玉章老师课题组招收人工智能全奖博士/博后"
    - "Credible plan-driven RAG method for Multi-hop Question Answering"
    - "BrainCodec: Neural fMRI codec for the decoding of cognitive brain states"
    - "DreamO: A Unified Framework for Image Customization"
    - "LLaVA Needs More Knowledge: Retrieval Augmented Natural Language Generation with Knowledge Graph for Explaining Thoracic Pathologies"
    - "Unchecked and Overlooked: Addressing the Checkbox Blind Spot in Large Language Models with CheckboxQA"
    - "The Bitter Lesson Learned from 2,000+ Multilingual Benchmarks"
    - "A Comprehensive Survey in LLM(-Agent) Full Stack Safety: Data, Training and Deployment"
    - "Unchecked and Overlooked: Addressing the Checkbox Blind Spot in Large Language Models with CheckboxQA"
    - "Cooperative Speech, Semantic Competence, and AI"
    - "Reflexive Prompt Engineering: A Framework for Responsible Prompt Engineering and Interaction Design"
    - "Transformers for Complex Query Answering over Knowledge Hypergraphs"
    - "博士申请 | 澳门大学计算机系郑哲东老师课题组招收多模态方向全奖博士生"
    - "AMD AI PC大赛重磅来袭！13万奖金池，NPU算力免费用，速来组队瓜分奖金！"
    - "博士申请 | 中佛罗里达大学计算机系尚玉章老师课题组招收人工智能全奖博士/博后"
    - "导师放养，偷偷发了顶会。。。"
    - "AAAI 2025 | 开放集跨网络节点分类！海大团队提出排除未知类别的对抗图域对齐"
    - "北京/杭州内推 | 阿里通义实验室对话智能团队招聘LLM多轮对话方向研究实习生"
    - "ACM MM 2025 LGM3A研讨会征稿：探索大模型与多模态的融合创新"
    - "北京/杭州内推 | 淘天集团直播AIGC团队招聘多模态内容理解方向算法实习生"
    - "博士申请 | 西湖大学吴泰霖老师招收AI for Science方向博士/博后/实习生"
    - "陶哲轩：感谢ChatGPT，4小时独立完成了一个开源项目"
    - "因为盲审没过，被延毕了……"
  # embedding_json: ./configs/score_proj_embedding.json

sources:
    # - func: infiv.spiders.zhihu.get_info
    #   url: "https://www.zhihu.com"
    #   subject: "feed"
    # - func: infiv.spiders.bilibili.get_info
    #   url: "https://www.bilibili.com"
    #   subject: "feed"
    # - func: infiv.spiders.bioxriv.get_info
    #   url: "https://www.biorxiv.org/collection/bioinformatics"
    #   subject: "paper"

    ## daily arxiv update
    # - func: infiv.spiders.rsshub.cool_paper_arxiv.get_info
    #   url: "http://localhost:1200/papers/arxiv/cs.CV?limit=500"
    #   subject: "paper"
    # - func: infiv.spiders.rsshub.cool_paper_arxiv.get_info
    #   url: "http://localhost:1200/papers/arxiv/cs.CL?limit=500"
    #   subject: "paper"
    # - func: infiv.spiders.rsshub.cool_paper_arxiv.get_info
    #   url: "http://localhost:1200/papers/arxiv/cs.RO?limit=500"
    #   subject: "paper RO"
    
    # spider for arxiv from arxiv api
    # support: expired_date but with time lagging ~1d
    - func: infiv.spiders.arxiv.get_info
      url: cs.CV
      subject: "paper"
    - func: infiv.spiders.arxiv.get_info
      url: cs.CL
      subject: "paper"
    - func: infiv.spiders.arxiv.get_info
      url: cs.RO
      subject: "paper"

    # - func: infiv.spiders.rsshub.cool_paper_arxiv.get_info
    #   url: "http://localhost:1200/papers/arxiv/cs.AI?limit=500"
    #   subject: paper
    # - func: infiv.spiders.rsshub.default.get_info
    #   url: "http://localhost:1200/nature/research"
    #   subject: paper
    # - func: infiv.spiders.rsshub.default.get_info
    #   url: "https://mshibanami.github.io/GitHubTrendingRSS/daily/all.xml"
    #   subject: coding
    
    - func: infiv.spiders.rsshub.default.get_info
      url: "https://wechat2rss.xlab.app/feed/51e92aad2728acdd1fda7314be32b16639353001.xml"  # 机器之心
      subject: "feed"
    - func: infiv.spiders.rsshub.default.get_info
      url: "https://wechat2rss.xlab.app/feed/3be891c2f4e526629ab055a297cc2cd6c1f0a563.xml"  # paper weekly
      subject: "feed"
