rerank:
  likes:
    - "DeepSeek-R1: Incentivizing Reasoning Capability in LLMs via Reinforcement Learning"
    - "QWEN2.5-MATH TECHNICAL REPORT: TOWARD MATHEMATICAL EXPERT MODEL VIA SELF-IMPROVEMENT"
    - "DeepSeekMath: Pushing the Limits of Mathematical Reasoning in Open Language Models"
    - "Seed-Thinking-v1.5: Advancing Superb Reasoning Models with Reinforcement Learning"
    - "VAPO: Efficient and Reliable Reinforcement Learning for Advanced Reasoning Tasks"
    - "Critique Fine-Tuning: Learning to Critique is More Effective than Learning to Imitate"
    - "SFT Memorizes, RL Generalizes: A Comparative Study of Foundation Model Post-training"
    - "Does Reinforcement Learning Really Incentivize Reasoning Capacity in LLMs Beyond the Base Model?"
    - "Chain-of-thought prompting elicits reasoning in large language models"
    - "What’s behind ppo’s collapse in long-cot? value optimization holds the secret"
  dislikes:
    - "RobustEMD: Domain Robust Matching for Cross-domain Few-shot Medical Image Segmentation"
    - "Semantic Segmentation of Unmanned Aerial Vehicle Remote Sensing Images using SegFormer"
    - "Y-CA-Net: A Convolutional Attention Based Network for Volumetric Medical Image Segmentation"
    - "LightM-UNet: Mamba Assists in Lightweight UNet for Medical Image Segmentation"
    - "Denoising diffusion probabilistic models for 3D medical image generation"
    - "The Segment Anything Model (SAM) for Remote Sensing Applications: From Zero to One Shot"
    - "OpenAI融资70亿，只剩孤家寡人？众人怒揭奥特曼真面目"
    - "Pika 1.5重磅升级！万物皆可爆炸，搞笑特效全网病毒式疯传"
    - "MIT系初创打破Transformer霸权！液体基础模型刷新SOTA，非GPT架构首次显著超越Transformer"
    - "Ilya预言错了！华人Nature一作给RLHF“判死刑”，全球大模型都不可靠"
    - "“群体智能”剑指AGI革命！国产架构挑战Transformer霸权，首款非Attention模型更新"
    - "FedBiP: Heterogeneous One-Shot Federated Learning with Personalized Latent Diffusion Models"
    - "Learning De-Biased Representations for Remote-Sensing Imagery"
    - "Brain Mapping with Dense Features: Grounding Cortical Semantic Selectivity in Natural Images With Vision Transformers"
    - "Art Forgery Detection using Kolmogorov Arnold and Convolutional Neural Networks"
    - "Synthetic Generation of Dermatoscopic Images with GAN and Closed-Form Factorization"
    - "BrainCodec: Neural fMRI codec for the decoding of cognitive brain states"
    - "DreamO: A Unified Framework for Image Customization"
    - "LLaVA Needs More Knowledge: Retrieval Augmented Natural Language Generation with Knowledge Graph for Explaining Thoracic Pathologies"
    - "Unchecked and Overlooked: Addressing the Checkbox Blind Spot in Large Language Models with CheckboxQA"
    - "The Bitter Lesson Learned from 2,000+ Multilingual Benchmarks"
    - "A Comprehensive Survey in LLM(-Agent) Full Stack Safety: Data, Training and Deployment"
    - "Unchecked and Overlooked: Addressing the Checkbox Blind Spot in Large Language Models with CheckboxQA"
  # embedding_json: ./configs/score_proj_embedding.json

sources:
    # - func: infiv.spiders.zhihu.get_info
    #   url: "https://www.zhihu.com"
    #   subject: "feed"
    # - func: infiv.spiders.bilibili.get_info
    #   url: "https://www.bilibili.com"
    #   subject: "feed"
    # - func: infiv.spiders.bioxriv.get_info
    #   url: "https://www.biorxiv.org/collection/bioinformatics"
    #   subject: "paper"
    - func: infiv.spiders.rsshub.cool_paper_arxiv.get_info
      url: "http://localhost:1200/papers/arxiv/cs.CV?limit=500"
      subject: "paper"
    - func: infiv.spiders.rsshub.cool_paper_arxiv.get_info
      url: "http://localhost:1200/papers/arxiv/cs.CL?limit=500"
      subject: "paper"
    - func: infiv.spiders.rsshub.cool_paper_arxiv.get_info
      url: "http://localhost:1200/papers/arxiv/cs.RO?limit=500"
      subject: "paper RO"
    # - func: infiv.spiders.rsshub.cool_paper_arxiv.get_info
    #   url: "http://localhost:1200/papers/arxiv/cs.AI?limit=500"
    #   subject: paper
    # - func: infiv.spiders.rsshub.default.get_info
    #   url: "http://localhost:1200/nature/research"
    #   subject: paper
    # - func: infiv.spiders.rsshub.default.get_info
    #   url: "https://mshibanami.github.io/GitHubTrendingRSS/daily/all.xml"
    #   subject: coding
    
    - func: infiv.spiders.rsshub.default.get_info
      url: "https://wechat2rss.xlab.app/feed/51e92aad2728acdd1fda7314be32b16639353001.xml"  # 机器之心
      subject: "feed"
    - func: infiv.spiders.rsshub.default.get_info
      url: "https://wechat2rss.xlab.app/feed/3be891c2f4e526629ab055a297cc2cd6c1f0a563.xml"  # paper weekly
      subject: "feed"
