name: infiv
on:
  schedule:
    - cron:  '0 22 * * *'    # 22:00 GTM
  workflow_dispatch:

jobs:
  push:
    runs-on: ubuntu-latest
    env:
      EXPIRED_DAYTIME: "2024/10/04 23:59"
    steps:
    - uses: actions/checkout@v4
    - name: checkout rsshub modified
      uses: actions/checkout@v4
      with:
        repository: ValMystletainn/RSSHub
        path: ./RSSHub
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - uses: actions/setup-node@v4
      with:
        node-version: 22.x
    - name: rsshub server setup
      run: | # It should wait for ready but we have to install other dependencies so don't sleep now
        cd RSSHub
        npm install
        npm run build
        npm run start &
    - name: install dependencies
      run: cd ${{ github.workspace }} && pip install -e .[rss] && npm install -g mystmd
    - name: fetch content and build
      run:  python -m infiv build
    - name: to myst pages
      run:  myst build --html
    - uses: actions/upload-artifact@v4
      with:
        path: output.md
    # TODO github page setting
    # - uses: actions/upload-pages-artifact@v1
    #   with:
    #     path: ./_build/html

