name: infiv
on:
  schedule:
    - cron:  '30 3 * * *'    # 3:30 GTM
  workflow_dispatch:

permissions:
  contents: read
  issues: write  # allow writing to issue
  pages: write

jobs:
  push:
    runs-on: ubuntu-latest
    env:
      EXPIRED_DAYTIME: "2024/10/04 23:59"
      ZHIHU_COOKIE: ${{ secrets.ZHIHU_COOKIE }}
    steps:
    - uses: actions/checkout@v4
    - name: checkout rsshub modified
      uses: actions/checkout@v4
      with:
        repository: ValMystletainn/RSSHub
        path: ./RSSHub
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    # - uses: actions/setup-node@v4
    #   with:
    #     node-version: 22.x
    # - name: rsshub server setup
    #   run: | # It should wait for ready but we have to install other dependencies so don't sleep now
    #     cd RSSHub
    #     npm install
    #     npm run build
    #     npm run start &
    - name: install dependencies
      run: |
        cd ${{ github.workspace }}
        pip install -e .[rss]
        # npm install -g mystmd
    - name: fetch content and build
      run:  python -m infiv build
    # - name: to myst pages
    #   run:  myst build --html
    - uses: actions/upload-artifact@v4
      with:
        path: output.md
        # path: ./_build/html
    # TODO github page setting
    # - uses: actions/upload-pages-artifact@v1
    #   with:
    #     path: ./_build/html
    
    - name: Upload markdown to issue
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        ISSUE_TITLE="Daily Report $(date '+%Y-%m-%d %H:%M:%S')"
        ISSUE_TITLE=$(echo "$ISSUE_TITLE" | jq -R .)
        ISSUE_BODY=$(cat output.md | jq -Rs .)
        # Create a new issue and upload the markdown content
        curl -s -X POST \
          -H "Authorization: token $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/issues \
          -d '{"title":"${ISSUE_TITLE}", "body":"I'\''m having a problem with this upload.", "labels":["report"]}'

